@startuml
class Persona {
    # protected rut: String
    # protected nombre: String
    # protected apellidoP: String
    # protected apellidoM: String
    # protected fechaNac: Date

    + public verCalificacion(): Void
    + public mensajear(): Void
}

class Docente {
    - private asignatura: String

    + public adjuntarMaterial(): Void
    + public registrarCalificacion(): Void
}

class Estudiante {
    - private carrera: String
    - private regular: Boolean
    - private beneficio: Boolean

    + public vizualizarMaterial(): Void
    + public dearrollarEvaluacion(): Void
    + public adjuntarEvaluacion(): Void
    + public solicitarBeneficio(): Void
}

class Curso {
    - private departamento: String
    - private profJefe: String
    - private duracion: Integer
    - private posgrado: Boolean
    - private periodo: String
    - private cantidadMatri: Integer

    + public asignarJefeCarr(): Void
    + public registrarPeriodo(): Void
    + public sumarMatri(): Void
}

class Asignatura {
    - private semestre: Integer
    - private anio: Integer
    - private departamento: String
    - private profesor: String

    + public asignarProfe(): Void
    + public promedioNotas(): Void
    + public compartirInfo(): Void 
}

Docente --|> Persona
Estudiante --|> Persona
Asignatura --o "1..*" Curso
Estudiante "1..*" -- Asignatura
Estudiante *-- "1" Curso
Docente *-- "1..*" Curso
Docente "1..*" -- "1..*" Asignatura

@enduml